// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kajikentaro/meeting-reminder/services (interfaces: MicrosoftRepository,UI)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_microsoft_repository.go -package=mocks . MicrosoftRepository,UI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMicrosoftRepository is a mock of MicrosoftRepository interface.
type MockMicrosoftRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMicrosoftRepositoryMockRecorder
	isgomock struct{}
}

// MockMicrosoftRepositoryMockRecorder is the mock recorder for MockMicrosoftRepository.
type MockMicrosoftRepositoryMockRecorder struct {
	mock *MockMicrosoftRepository
}

// NewMockMicrosoftRepository creates a new mock instance.
func NewMockMicrosoftRepository(ctrl *gomock.Controller) *MockMicrosoftRepository {
	mock := &MockMicrosoftRepository{ctrl: ctrl}
	mock.recorder = &MockMicrosoftRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMicrosoftRepository) EXPECT() *MockMicrosoftRepositoryMockRecorder {
	return m.recorder
}

// FetchCalendarEvents mocks base method.
func (m *MockMicrosoftRepository) FetchCalendarEvents() ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCalendarEvents")
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCalendarEvents indicates an expected call of FetchCalendarEvents.
func (mr *MockMicrosoftRepositoryMockRecorder) FetchCalendarEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCalendarEvents", reflect.TypeOf((*MockMicrosoftRepository)(nil).FetchCalendarEvents))
}

// MockUI is a mock of UI interface.
type MockUI struct {
	ctrl     *gomock.Controller
	recorder *MockUIMockRecorder
	isgomock struct{}
}

// MockUIMockRecorder is the mock recorder for MockUI.
type MockUIMockRecorder struct {
	mock *MockUI
}

// NewMockUI creates a new mock instance.
func NewMockUI(ctrl *gomock.Controller) *MockUI {
	mock := &MockUI{ctrl: ctrl}
	mock.recorder = &MockUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUI) EXPECT() *MockUIMockRecorder {
	return m.recorder
}

// ShowMeetingReminder mocks base method.
func (m *MockUI) ShowMeetingReminder(message, location string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowMeetingReminder", message, location)
}

// ShowMeetingReminder indicates an expected call of ShowMeetingReminder.
func (mr *MockUIMockRecorder) ShowMeetingReminder(message, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowMeetingReminder", reflect.TypeOf((*MockUI)(nil).ShowMeetingReminder), message, location)
}
